### ISSUE TITLE
Add a "why" to README

### ISSUE THREAD

**Issue by patcon** [opennorth/scrapers-ca-ruby#10]
Might be interesting to clarify what the goals of this repo vs the python one are. Is it simply that ruby seems better for scraping? Will this repo hold the "next generation" of canadian scrapers? Would a new city best be added to this repo? Will this be the one that is improved upon or kept up-to-date?

These are just the sort of things I'd wonder about when finding this, and the README currently doesn't clear up those points :)

**Comment by jpmckinney** [comment]
No, you shouldn't contribute anything to this repo. I use it for some scrapers that are very specialized which I find easier to write in Ruby.

**Comment by patcon** [comment]
ok, perfect! Your call, but that sort of thing is helpful in a readme, so perusers know what's up and why something exists

**Comment by jpmckinney** [comment]
Sure, if it comes up again, I'll update the readme!
